# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album',
            field=models.ManyToManyField(blank=True, default='', to='imager_profile.Photo'),
        ),
    ]
