# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=models.CharField(choices=[('NKD3300', 'NikonD3300'), ('CNT6I', 'CanonT6i'), ('CNMKD5III', 'Canon5dMarkIII'), ('SNYA99II', 'SonyAlphaA99II')], default='CNT6I', max_length=20),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_styles',
            field=models.TextField(choices=[('70s', 'Classic retro style with filters to match.'), ('NOIR', 'Bold black and white photos.'), ('BOKEH', 'Blurry background with subject in focus.'), ('STUDIO', 'Profile shots with bright lighting and white backdrop.'), ('STD', 'Regular shots with no filters.')], default='STD', max_length=400),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=models.TextField(choices=[('ULT', '20 photos, provided lighting equipment, additional photo editing post-production.'), ('MEGA', '15 photos, provided lighting equipment, 5 free prints of your choice.'), ('BSC', '10 photos, 3 free prints of your choice.')], default='MEGA', max_length=2000),
        ),
    ]
