# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20171121_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='user',
        ),
    ]
