# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 00:13
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_auto_20171128_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NikonD3300', 'NikonD3300'), ('CanonT6i', 'CanonT6i'), ('Canon5dMarkIII', 'Canon5dMarkIII'), ('SonyAlphaA99II', 'SonyAlphaA99II')], default='CanonT6i', max_length=20),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_styles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[("70's", 'Classic retro style with filters to match.'), ('Noir', 'Bold black and white photos.'), ('Bokeh', 'Blurry background with subject in focus.'), ('Studio', 'Profile shots with bright lighting and white backdrop.'), ('Standard', 'Regular shots with no filters.')], default='Standard', max_length=400),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ultimate-Service Pack', '20 photos, provided lighting equipment, additional photo editing post-production.'), ('Mega-Service Pack', '15 photos, provided lighting equipment, 5 free prints of your choice.'), ('Basic-Service Pack', '10 photos, 3 free prints of your choice.')], default='Mega-Service Pack', max_length=2000),
        ),
    ]
