# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('PRIVATE', 'This album is private'), ('SHARED', 'This album is shared'), ('PUBLIC', 'This album is public')], default='PRIVATE', max_length=200),
        ),
    ]
