# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, default='', related_name='albums', to='imager_images.Photo'),
        ),
    ]
