# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20171204_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
